"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";
import Image from "next/image";
import { Wind, Waves, Mountain, Check, Play, Pause } from "lucide-react";

/* -----------------------------
   TYPES
------------------------------ */

type SiteType = "refinery" | "landfill" | "highway";
type LayerType = "air" | "soil" | "water";

interface Pollutant {
  code: string;
  name: string;
  description: string;
  color: string;
}

interface LayerPollutants {
  air: Pollutant[];
  soil: Pollutant[];
  water: Pollutant[];
}

interface SiteConfig {
  id: SiteType;
  name: string;
  image: string;
  pollutants: LayerPollutants;
}

/* -----------------------------
   CONFIG
------------------------------ */

const SITES: SiteConfig[] = [
  {
    id: "refinery",
    name: "Oil Refinery",
    image: "/pollution/oil refinery.png",

    pollutants: {
      air: [
        {
          code: "SOx",
          name: "Sulfur Oxides",
          description:
            "Air pollutant emitted from crude oil processing that contributes to respiratory illness and acid rain.",
          color: "#ED3434",
        },
        {
          code: "NOx",
          name: "Nitrogen Oxides",
          description:
            "Combustion-related air pollutants that react with sunlight to create ground-level ozone.",
          color: "#3B1CC4",
        },
      ],

      soil: [
        {
          code: "Pb",
          name: "Lead",
          description:
            "A highly toxic heavy metal that accumulates in the body over time. Can cause neurological, cardiovascular, kidney, and reproductive issues.",
          color: "#6B4E2E",
        },
      ],

      water: [
        {
          code: "C₆H₆",
          name: "Benzene",
          description:
            "Highly toxic carcinogen, can damage the blood and cause cancer and leukemia.",
          color: "#00C2FF",
        },
      ],
    },
  },

  {
    id: "landfill",
    name: "Landfill",
    image: "/pollution/landfill.png",

    pollutants: {
      air: [
        {
          code: "CH₄",
          name: "Methane",
          description: "Potent greenhouse gas generated by decomposing waste.",
          color: "#878A00",
        },
      ],

      soil: [
        {
          code: "Hg",
          name: "Mercury",
          description:
            "Leaked from batteries and light bulbs, can cause neurological and physiological damage.",
          color: "#4F4F4F",
        },
      ],

      water: [
        {
          code: "Leachate",
          name: "Leachate",
          description:
            "Contaminated liquid formed when rainwater filters through landfill waste.",
          color: "#00B3A7",
        },
      ],
    },
  },

  {
    id: "highway",
    name: "Highway",
    image: "/pollution/highway.png",

    pollutants: {
      air: [
        {
          code: "PM2.5",
          name: "Fine Particulate Matter",
          description:
            "Microscopic soot particles that penetrate deep into the lungs.",
          color: "#4F4F4F",
        },
      ],

      soil: [
        {
          code: "Zinc",
          name: "Zinc",
          description:
            "Vehicle wear deposits heavy metals into roadside soils.",
          color: "#7D5A50",
        },
      ],

      water: [
        {
          code: "Runoff",
          name: "Road Runoff",
          description:
            "Stormwater runoff carries oil, brake dust, and chemicals into waterways.",
          color: "#3ABEFF",
        },
      ],
    },
  },
];

/* -----------------------------
   SCENE
------------------------------ */

function MapScene({
  children,
  showSoil,
  showWater,
}: {
  children: ReactNode;
  showSoil: boolean;
  showWater: boolean;
}) {
  return (
    <div className="relative w-full min-h-[95vh] overflow-hidden bg-[#A9DF8E] text-white select-none">
      <Image
        src="/pollution/bg-pollution.png"
        alt="background"
        fill
        priority
        className="object-cover"
      />

      {/* underground */}
      {(showSoil || showWater) && (
        <div className="absolute bottom-0 left-0 right-0 h-[42%] overflow-hidden z-0">
          {/* soil */}
          {showSoil && (
            <div className="absolute inset-0 bg-gradient-to-b from-[#4D331F] to-[#24160D]" />
          )}

          {/* water */}
          {showWater && (
            <>
              <div className="absolute top-[45%] left-0 right-0 h-[2px] bg-cyan-200/50" />

              <div className="absolute bottom-0 left-0 right-0 h-[55%] bg-gradient-to-b from-cyan-400/10 to-cyan-500/25 backdrop-blur-[2px]" />
            </>
          )}
        </div>
      )}

      {children}
    </div>
  );
}

/* -----------------------------
   TOOLTIP
------------------------------ */

function Tooltip({ pollutant }: { pollutant: Pollutant }) {
  return (
    <div
      className="absolute right-full mr-3 bg-[#2B2D24] text-white p-3.5 rounded-xl shadow-2xl z-[999]"
      style={{ width: 200, transform: "translateY(-10%)" }}
    >
      <div className="text-sm font-extrabold">{pollutant.name}</div>

      <div className="text-xs text-gray-300 mt-1.5 leading-relaxed">
        {pollutant.description}
      </div>
    </div>
  );
}

/* -----------------------------
   AIR LAYER
------------------------------ */

interface AirParticle {
  id: number;
  x: number;
  y: number;
  vx: number;
  vy: number;
  life: number;
  large: boolean;
  pollutant: Pollutant;
}

function AirLayer({
  active,
  pollutants,
  resetKey,
}: {
  active: boolean;
  pollutants: Pollutant[];
  resetKey: number;
}) {
  const [particles, setParticles] = useState<AirParticle[]>([]);
  const [hovered, setHovered] = useState<number | null>(null);

  // Clear particles when site changes
  useEffect(() => {
    setParticles([]);
  }, [resetKey]);

  useEffect(() => {
    if (!active) return;

    const interval = setInterval(() => {
      setParticles((prev) => {
        const updated = prev
          .map((p) => ({
            ...p,
            x: p.x + p.vx,
            y: p.y + p.vy,
            life: p.life - (p.large ? 0.005 : 0.015),
          }))
          .filter((p) => p.life > 0);

        const pollutant =
          pollutants[Math.floor(Math.random() * pollutants.length)];

        const large = Math.random() < 0.05;

        updated.push({
          id: Date.now() + Math.random(),
          x: 50 + (Math.random() - 0.5) * 8,
          y: 52,
          vx: (Math.random() - 0.5) * 0.8,
          vy: (Math.random() - 0.8) * 0.7,
          life: 1.2,
          large,
          pollutant,
        });

        return updated;
      });
    }, 90);

    return () => clearInterval(interval);
  }, [active, pollutants]);

  return (
    <>
      {particles.map((p) => {
        const isHovered = hovered === p.id;

        return (
          <div
            key={p.id}
            className="absolute"
            style={{
              left: `${p.x}%`,
              top: `${p.y}%`,
              transform: "translate(-50%, -50%)",
              zIndex: isHovered ? 100 : 20,
            }}
            onMouseEnter={() => p.large && setHovered(p.id)}
            onMouseLeave={() => setHovered(null)}
          >
            {p.large ? (
              <div className="relative">
                {isHovered && <Tooltip pollutant={p.pollutant} />}

                <div
                  className="w-20 h-20 rounded-full flex items-center justify-center text-lg distressed-text-normal font-black shadow-xl"
                  style={{
                    background: p.pollutant.color,
                    opacity: p.life,
                  }}
                >
                  {p.pollutant.code}
                </div>
              </div>
            ) : (
              <div
                className="rounded-full blur-[1px]"
                style={{
                  width: 12,
                  height: 12,
                  background: p.pollutant.color,
                  opacity: p.life * 0.7,
                }}
              />
            )}
          </div>
        );
      })}
    </>
  );
}

/* -----------------------------
   SOIL LAYER
------------------------------ */

interface SoilBlob {
  id: number;
  x: number;
  y: number;
  size: number;
  pollutant: Pollutant;
}

function SoilLayer({
  active,
  pollutants,
  resetKey,
}: {
  active: boolean;
  pollutants: Pollutant[];
  resetKey: number;
}) {
  const [blobs, setBlobs] = useState<SoilBlob[]>([]);
  const [hovered, setHovered] = useState<number | null>(null);

  // Clear blobs when site changes
  useEffect(() => {
    setBlobs([]);
  }, [resetKey]);

  useEffect(() => {
    if (!active) return;

    const interval = setInterval(() => {
      const pollutant =
        pollutants[Math.floor(Math.random() * pollutants.length)];

      setBlobs((prev) => [
        ...prev,
        {
          id: Date.now() + Math.random(),
          x: 10 + Math.random() * 80, // spread across full width
          y: 70 + Math.random() * 10,
          size: 60 + Math.random() * 60,
          pollutant,
        },
      ]);
    }, 1800); // slower generation

    return () => clearInterval(interval);
  }, [active, pollutants]);

  return (
    <>
      {blobs.map((blob) => {
        const isHovered = hovered === blob.id;

        return (
          <div
            key={blob.id}
            className="absolute"
            style={{
              left: `${blob.x}%`,
              top: `${blob.y}%`,
              transform: "translate(-50%, -50%)",
              zIndex: isHovered ? 120 : 5,
            }}
            onMouseEnter={() => setHovered(blob.id)}
            onMouseLeave={() => setHovered(null)}
          >
            {isHovered && <Tooltip pollutant={blob.pollutant} />}

            <div
              className="rounded-full animate-pulse cursor-pointer flex items-center justify-center text-white font-black text-sm distressed-text-normal"
              style={{
                width: blob.size,
                height: blob.size,
                background: blob.pollutant.color,
                opacity: 0.78,
              }}
            >
              {blob.pollutant.code}
            </div>
          </div>
        );
      })}
    </>
  );
}

/* -----------------------------
   WATER LAYER
------------------------------ */

interface WaterStream {
  id: number;
  x: number;
  y: number;
  width: number;
  pollutant: Pollutant;
}

function WaterLayer({
  active,
  pollutants,
  resetKey,
}: {
  active: boolean;
  pollutants: Pollutant[];
  resetKey: number;
}) {
  const [streams, setStreams] = useState<WaterStream[]>([]);
  const [hovered, setHovered] = useState<number | null>(null);

  // Clear streams when site changes
  useEffect(() => {
    setStreams([]);
  }, [resetKey]);

  useEffect(() => {
    if (!active) return;

    const interval = setInterval(() => {
      const pollutant =
        pollutants[Math.floor(Math.random() * pollutants.length)];

      setStreams((prev) => [
        ...prev,
        {
          id: Date.now() + Math.random(),
          x: 5 + Math.random() * 70, // spread across width (flows right via animation)
          y: 82 + Math.random() * 6,
          width: 70 + Math.random() * 70,
          pollutant,
        },
      ]);
    }, 1600); // slower generation

    return () => clearInterval(interval);
  }, [active, pollutants]);

  return (
    <>
      {streams.map((stream) => {
        const isHovered = hovered === stream.id;

        return (
          <div
            key={stream.id}
            className="absolute cursor-pointer"
            style={{
              left: `${stream.x}%`,
              top: `${stream.y}%`,
              zIndex: isHovered ? 150 : 2,
            }}
            onMouseEnter={() => setHovered(stream.id)}
            onMouseLeave={() => setHovered(null)}
          >
            {isHovered && <Tooltip pollutant={stream.pollutant} />}

            <div
              className="rounded-full animate-[flow_7s_linear_forwards] flex items-center justify-center text-lg font-black text-white distressed-text-normal"
              style={{
                width: stream.width,
                height: stream.width,
                background: stream.pollutant.color,
                opacity: 0.72,
              }}
            >
              {stream.pollutant.code}
            </div>
          </div>
        );
      })}

      <style jsx>{`
        @keyframes flow {
          from {
            transform: translateX(0px);
            opacity: 0.18;
          }
          to {
            transform: translateX(420px);
            opacity: 0;
          }
        }
      `}</style>
    </>
  );
}

/* -----------------------------
   FACILITY
------------------------------ */

function Facility({ site }: { site: SiteConfig }) {
  return (
    <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/3 z-20 pointer-events-none">
      <div className="relative w-[480px] h-[480px]">
        <Image
          src={site.image}
          alt={site.name}
          fill
          className="object-contain"
        />
      </div>
    </div>
  );
}

/* -----------------------------
   CONTROLS
------------------------------ */

function Controls({
  siteId,
  setSiteId,
  playing,
  setPlaying,
  layers,
  toggleLayer,
}: any) {
  const LAYER_CONFIG = {
    air: {
      icon: Wind,
      label: "Air",
    },
    soil: {
      icon: Mountain,
      label: "Soil",
    },
    water: {
      icon: Waves,
      label: "Water",
    },
  };

  return (
    <>
      {/* site type */}
      <div className="absolute top-6 left-0 right-0 flex flex-col items-center z-40">
        <div className="text-sm text-black/70 mb-3">Site Type</div>

        <div className="flex gap-3">
          {SITES.map((s) => {
            const active = siteId === s.id;

            return (
              <button
                key={s.id}
                onClick={() => setSiteId(s.id)}
                className={`px-5 py-2 rounded-full text-sm font-semibold transition-colors ${
                  active ? "bg-[#00A651]" : "bg-[#252A1E] hover:bg-[#343b2b]"
                }`}
              >
                {s.name}
              </button>
            );
          })}
        </div>
      </div>

      {/* play */}
      <div className="absolute top-28 left-0 right-0 flex justify-center z-40">
        <button
          onClick={() => setPlaying(!playing)}
          className="px-6 py-2.5 bg-black rounded-full text-sm font-semibold flex items-center gap-2"
        >
          {playing ? (
            <>
              <Pause className="w-4 h-4 fill-white" />
              Pause simulation
            </>
          ) : (
            <>
              <Play className="w-4 h-4 fill-white" />
              Run simulation
            </>
          )}
        </button>
      </div>

      {/* layers */}
      <div className="absolute left-5 top-40 z-50">
        <div className="bg-white/30 backdrop-blur-md rounded-2xl p-4 w-[150px] border border-white/10">
          <div className="text-sm text-black/60 mb-4">Environmental Layers</div>

          {(
            Object.entries(LAYER_CONFIG) as [
              LayerType,
              {
                icon: any;
                label: string;
              }
            ][]
          ).map(([layer, config]) => {
            const Icon = config.icon;

            return (
              <label
                key={layer}
                className="flex items-center gap-3 px-3 py-3 rounded-xl hover:bg-black/5 cursor-pointer transition-colors"
              >
                <button
                  type="button"
                  onClick={() => toggleLayer(layer)}
                  className={`w-5 h-5 shrink-0 rounded border flex items-center justify-center transition-all ${
                    layers[layer]
                      ? "bg-white/80 border-white"
                      : "border-white/40 bg-transparent"
                  }`}
                >
                  {layers[layer] && (
                    <Check className="w-3.5 h-3.5 text-black stroke-[3]" />
                  )}
                </button>

                <Icon className="w-4 h-4 text-black/80" />

                <span className="text-sm text-black">{config.label}</span>
              </label>
            );
          })}
        </div>
      </div>
    </>
  );
}

/* -----------------------------
   MAIN
------------------------------ */

export function PollutionSimulation() {
  const [siteId, setSiteId] = useState<SiteType>("refinery");
  const [resetKey, setResetKey] = useState(0);

  const [playing, setPlaying] = useState(false);

  const [layers, setLayers] = useState({
    air: true,
    soil: true,
    water: true,
  });

  const site = useMemo(() => SITES.find((s) => s.id === siteId)!, [siteId]);

  function toggleLayer(layer: LayerType) {
    setLayers((prev) => ({
      ...prev,
      [layer]: !prev[layer],
    }));
  }

  function handleSetSiteId(id: SiteType) {
    setSiteId(id);
    setResetKey((k) => k + 1);
  }

  return (
    <MapScene showSoil={layers.soil} showWater={layers.water}>
      <Facility site={site} />

      {layers.air && (
        <AirLayer
          active={playing}
          pollutants={site.pollutants.air}
          resetKey={resetKey}
        />
      )}

      {layers.soil && (
        <SoilLayer
          active={playing}
          pollutants={site.pollutants.soil}
          resetKey={resetKey}
        />
      )}

      {layers.water && (
        <WaterLayer
          active={playing}
          pollutants={site.pollutants.water}
          resetKey={resetKey}
        />
      )}

      <Controls
        siteId={siteId}
        setSiteId={handleSetSiteId}
        playing={playing}
        setPlaying={setPlaying}
        layers={layers}
        toggleLayer={toggleLayer}
      />

      {/* instructions */}
      <div className="absolute left-5 top-5 z-40 max-w-[280px] rounded-2xl bg-white/65 backdrop-blur-sm p-4 text-sm text-black shadow-xl">
        <p className="leading-relaxed opacity-80">
          Toggle environmental layers to see the pollutants generated by each
          site. Hover over pollutants to learn more about their impacts.
        </p>
      </div>
    </MapScene>
  );
}
