"use client";

import { useState, useEffect, useMemo, type ReactNode } from "react";
import Image from "next/image";

/* -----------------------------
   TYPES
------------------------------ */

type SiteType = "refinery" | "landfill" | "highway";

interface Pollutant {
  code: string;
  name: string;
  description: string;
  color: string;
}

interface SiteConfig {
  id: SiteType;
  name: string;
  image: string;
  pollutants: Pollutant[];
}

/* -----------------------------
   CONFIG
------------------------------ */

const SITES: SiteConfig[] = [
  {
    id: "refinery",
    name: "Oil Refinery",
    image: "/pollution/oil refinery.png",
    pollutants: [
      {
        code: "SOx",
        name: "Sulfur Oxides",
        description:
          "Emitted from crude oil processing. Causes severe respiratory irritation and contributes to acid rain.",
        color: "#ED3434",
      },
      {
        code: "NOx",
        name: "Nitrogen Oxides",
        description:
          "Produced during high-temperature fuel combustion. Reacts with sunlight to create toxic ground-level ozone.",
        color: "#3B1CC4",
      },
    ],
  },
  {
    id: "landfill",
    name: "Landfill",
    image: "/pollution/landfill.png",
    pollutants: [
      {
        code: "CH₄",
        name: "Methane",
        description:
          "Generated by anaerobic decomposition of waste. A potent greenhouse gas trapping atmospheric heat.",
        color: "#878A00",
      },
      {
        code: "H₂S",
        name: "Hydrogen Sulfide",
        description:
          "Produced by bacteria breaking down organic matter. Responsible for the distinct 'rotten egg' landfill odor.",
        color: "#FFAA00",
      },
    ],
  },
  {
    id: "highway",
    name: "Highway",
    image: "/pollution/highway.png",
    pollutants: [
      {
        code: "PM 2.5",
        name: "Fine Particulate Matter",
        description:
          "Microscopic soot particles from tire wear and exhaust that penetrate deep into lungs and the bloodstream.",
        color: "#4F4F4F",
      },
      {
        code: "CO",
        name: "Carbon Monoxide",
        description:
          "Toxic gas from incomplete vehicle fuel combustion. Binds to hemoglobin, reducing oxygen transport in body tissue.",
        color: "#948A76",
      },
    ],
  },
];

/* -----------------------------
   SCENE
------------------------------ */

function MapScene({ children }: { children: ReactNode }) {
  return (
    <div className="relative w-full min-h-[95vh] overflow-hidden bg-[#A9DF8E] text-white font-sans select-none">
      <Image
        src="/pollution/bg-pollution.png"
        alt="background"
        fill
        priority
        className="object-cover"
      />
      {children}
    </div>
  );
}

/* -----------------------------
   PARTICLES
------------------------------ */

interface Particle {
  id: number;
  x: number;
  y: number;
  vx: number;
  vy: number;
  life: number;
  size: "small" | "large";
  pollutant: Pollutant;
}

function ParticleLayer({
  active,
  site,
}: {
  active: boolean;
  site: SiteConfig;
}) {
  const [particles, setParticles] = useState<Particle[]>([]);
  const [hoveredParticleId, setHoveredParticleId] = useState<number | null>(
    null
  );

  useEffect(() => {
    setParticles([]);
    setHoveredParticleId(null);
  }, [site.id]);

  useEffect(() => {
    if (!active) return;

    const interval = setInterval(() => {
      setParticles((prev) => {
        const updated = prev
          .map((p) => ({
            ...p,
            x: p.x + p.vx,
            y: p.y + p.vy,
            life: p.life - (p.size === "small" ? 0.012 : 0.005),
          }))
          .filter((p) => p.life > 0);

        const pollutant =
          site.pollutants[Math.floor(Math.random() * site.pollutants.length)];

        const isLarge = Math.random() < 0.05;

        updated.push({
          id: Date.now() + Math.random(),
          x: 50 + (Math.random() - 0.5) * 6,
          y: 52,
          vx: (Math.random() - 0.5) * (isLarge ? 0.25 : 0.9),
          vy: (Math.random() - 0.8) * (isLarge ? 0.2 : 0.85),
          life: isLarge ? 1.6 : 1.3,
          size: isLarge ? "large" : "small",
          pollutant,
        });

        return updated;
      });
    }, 90);

    return () => clearInterval(interval);
  }, [active, site]);

  return (
    <>
      {particles.map((p) => {
        const isHovered = hoveredParticleId === p.id;

        return (
          <div
            key={p.id}
            className="absolute transition-opacity duration-150"
            style={{
              left: `${p.x}%`,
              top: `${p.y}%`,
              transform: "translate(-50%, -50%)",
              zIndex: isHovered ? 100 : p.size === "large" ? 40 : 10,
            }}
            onMouseEnter={() =>
              p.size === "large" && setHoveredParticleId(p.id)
            }
            onMouseLeave={() => setHoveredParticleId(null)}
          >
            {/* SMALL BACKGROUND CIRCLES */}
            {p.size === "small" && (
              <div
                className="rounded-full transition-transform duration-300"
                style={{
                  width: p.id % 2 === 0 ? 10 : 16,
                  height: p.id % 2 === 0 ? 10 : 16,
                  background: p.pollutant.color,
                  opacity: p.life * 0.8,
                }}
              />
            )}

            {/* LARGE NODE COMPONENT */}
            {p.size === "large" && (
              <div className="relative flex items-center justify-center cursor-pointer">
                {/* TOOLTIP: SHOWN ONLY ON HOVER */}
                {isHovered && (
                  <div
                    className="absolute right-full mr-3 bg-[#2B2D24] text-white p-3.5 rounded-xl shadow-2xl z-50 text-left transition-all"
                    style={{ width: 180, transform: "translateY(-10%)" }}
                  >
                    <div className="text-sm font-extrabold tracking-wide text-white">
                      {p.pollutant.name}
                    </div>
                    <div className="text-xs text-gray-300 mt-1.5 leading-relaxed">
                      {p.pollutant.description}
                    </div>
                    <div className="absolute top-1/2 -right-1.5 -translate-y-1/2 w-0 h-0 border-y-4 border-y-transparent border-l-4 border-l-[#2B2D24]" />
                  </div>
                )}

                {/* Main Labeled Chemical Node */}
                <div
                  className="rounded-full flex items-center justify-center font-black text-[11px] text-white tracking-tight select-none transition-transform hover:scale-110 shadow-md border border-white/10"
                  style={{
                    width: 80,
                    height: 80,
                    background: p.pollutant.color,
                    opacity: Math.min(p.life + 0.3, 1),
                  }}
                >
                  <span className="distressed-text text-center px-1 break-words leading-none text-lg">
                    {p.pollutant.code}
                  </span>
                </div>
              </div>
            )}
          </div>
        );
      })}
    </>
  );
}

/* -----------------------------
   FACILITY
------------------------------ */

function Facility({ site }: { site: SiteConfig }) {
  return (
    <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/3 z-20 pointer-events-none">
      <div className="relative w-120 h-120 mx-auto">
        <Image
          src={site.image}
          alt={site.name}
          fill
          className="object-contain"
          style={{ filter: "drop-shadow(0px 8px 12px rgba(0,0,0,0.08))" }}
        />
      </div>
    </div>
  );
}

/* -----------------------------
   CONTROLS
------------------------------ */

function Controls({ siteId, setSiteId, playing, setPlaying }: any) {
  return (
    <>
      {/* TOP PILLS */}
      <div className="absolute top-6 left-0 right-0 flex justify-center gap-3 z-30">
        {SITES.map((s) => {
          const isActive = siteId === s.id;
          return (
            <button
              key={s.id}
              onClick={() => {
                setSiteId(s.id);
                setPlaying(false);
              }}
              className={`px-5 py-2 rounded-full text-sm font-semibold tracking-wide transition-colors ${
                isActive
                  ? "bg-[#00A651] text-white shadow-md"
                  : "bg-[#252A1E] text-white hover:bg-[#343b2b]"
              }`}
            >
              {s.name}
            </button>
          );
        })}
      </div>

      {/* BOTTOM ACTION */}
      <div className="absolute top-18 left-0 right-0 flex flex-col items-center gap-1 z-30">
        <button
          onClick={() => setPlaying(!playing)}
          className="flex items-center gap-2 px-6 py-2.5 bg-black text-white rounded-full font-semibold text-sm shadow-xl hover:bg-neutral-900 transition-all active:scale-95"
        >
          {playing ? (
            <>
              <svg className="w-3 h-3 fill-current" viewBox="0 0 24 24">
                <path d="M6 19h4V5H6v14zm8-14v14h4V5h-4z" />
              </svg>
              Pause simulation
            </>
          ) : (
            <>
              <svg className="w-3 h-3 fill-current" viewBox="0 0 24 24">
                <path d="M8 5v14l11-7z" />
              </svg>
              Run simulation
            </>
          )}
        </button>
      </div>
    </>
  );
}

/* -----------------------------
   MAIN CONTAINER
------------------------------ */

export function PollutionSimulation() {
  const [siteId, setSiteId] = useState<SiteType>("refinery");
  const [playing, setPlaying] = useState(false);

  const site = useMemo(() => SITES.find((s) => s.id === siteId)!, [siteId]);

  return (
    <MapScene>
      <Facility site={site} />
      <ParticleLayer active={playing} site={site} />
      <Controls
        siteId={siteId}
        setSiteId={setSiteId}
        playing={playing}
        setPlaying={setPlaying}
      />
      {/* Instructions */}
      <div className="absolute left-4 top-4 z-20 max-w-[280px] rounded-xl bg-white/70 backdrop-blur-sm p-4 text-sm text-black shadow-lg">
        <p className="opacity-80 leading-relaxed">
          Run simulations to see what kinds of pollutants are generated by
          different facilities. Hover over the big particles to read more about
          them.
        </p>
      </div>
    </MapScene>
  );
}
